Dockerfile
reverting back to go 1.18, anything above throws an exception, reported in #45
=> New golang images do not build correctly for docker

.goreleaser.yaml, npm-install/config.js
To use chocolatey, we need to move to zip files. This move changes the build artifacts to be compressed using zip instead of compressing a tarball via gzip.
=> Moving build to a zip vs tarball

.github/workflows/publish.yaml, npm-install/postinstall.js, package.json
New windows build means we need to set the binary to be executable after install.
=> Updating build and npm packaging.

.github/workflows/publish.yaml
a 403 is being thrown and it’s giving me grief with chocolatey, so npm and docker will stuill work, even after chocolatey is being a pain
=> changing build to allow chocolatey to fail.

cmd/html_report.go
The build now happens on a windows runner, to be able to support windows. However when writing a file, the binary is not setting the correct permissions, the file cannot be read. If this can’t be resolved, I will need to split the build into a windows and linux run.
=> Strange windows permissions when generating html-report

go.mod, go.sum
a panic was detected online, the culprit was an NPE, it’s now been caught.
=> bumped libopenapi

go.mod, go.sum
still some concurrent map issues, but should prevent online blowups.
=> upgraded libopenapi to a mostly stable version.

cmd/report.go
report date created time is now formatted according to RFC 3339.
=> formatting time to RFC 3339 for report

.goreleaser.yaml, npm-install/config.js, npm-install/postinstall.js
reverted everything back to the olden times, no more direct windows builds, only linux. reverting back to the vacuum design which works consistently for npm.
=> v0.0.60 Damn you windows.

cmd/flatten_report.go, model/report.go
The flat report did not have the commit information.
I added code to copy the commit information from the report to the flat report.
=> OPENAPI: added commit information to flat report

builder/graph.go, builder/tree.go, cmd/console.go, cmd/html_report.go, cmd/report.go, cmd/summary.go, go.mod, go.sum
https://github.com/twinj/uuid was last updated in 2017 and has been archived since 2020.
Additionally `twinj/uuid` pulls in a non-existent `github.com/myesui/uuid` which causes `go mod download` to fail.
=> Use `google/uuid` rather than `twinj/uuid`

cmd/summary.go
I noticed that when `--markdown` is passed the summary just output the `total` as breaking changes, not the actual count of breaking changes. Additionally for non-markdown output the modified count was not being output.
=> Correct the counts output by `openapi-changes summary`

cmd/console.go, cmd/flatten_report.go, cmd/html_report.go, cmd/report.go, cmd/root.go, cmd/summary.go, git/github.go, git/read_local.go, git/read_local_test.go, model/report.go
This MR adds the `time-limit` option to restrict the number of changes by the number of days in the past.
Additionally, it adds a sha256 hash of each change in order to allow deduplication.
=> OPENAPI: added time-limit command and change hashing

cmd/summary.go
This behavior is consistent with how html-report behaves, and is desireable for CI environments such as GitHub Actions where the spinner output won't look near as pretty.
---
I'm attempting to embed openapi-changes into a GitHub workflow, so that I can have it error a check on a PR if a PR were to introduce any breaking changes. I'm using the summary markdown output feature, in an action a little like this:
```
name: 'Check for Breaking OAS Changes'
description: 'Compares the version of a spec against what is currently in main.'
inputs:
spec-to-scan: # local path to a spec to check for changes
description: 'Repository-local path to a spec to check for breaking changes.'
required: true
runs:
using: 'composite'
steps:
- uses: actions/checkout@v3
- name: Install pb33f/openapi-changes
uses: …
```
=> summary - suppress spinner if noColor is true

cmd/summary.go
A nil pointer check was required in a few places.
=> Addressed issue #155

cmd/console.go, cmd/html_report.go, cmd/report.go, cmd/root.go, cmd/summary.go, git/read_local.go, git/read_local_test.go
I'm trying to include openapi-changes in our GitHub Actions CI to detect breaking changes in pull requests. My approach to doing this was to take the number of commits made on a branch `n` (given by `github.event.pull_request.commits`) and passing `n+1` to `openapi-changes` via the `--limit` flag.
**Problem**
What I found was that the tool looks at the full local git history of the file, and uses the `--limit` flag to cut off after `n` commits. This leads to problems when a PR has `10` commits, but none or only some changed the OpenAPI spec being checked.
**Approach**
As a quick fix, this PR adds a `global-revisions` boolean flag, which is used to instruct `git` to list the history between specific revisions (i.e., `HEAD~(n+1)..HEAD`).
**Alternative Approaches**
I've seen #85 and I think …
=> Add global-revisions flag

cmd/report.go, git/read_local.go
I think I introduced a bug with #158. This should address it.
When processing the earliest commit of the commit history, no file content
outside the history is present. This means that no changes can be calculated
for the earliest commit.
This issue was likely always present but surfaced by the introduction of the `--global-revisions` flag. Previously, the issue would only appear when reaching the commit that introduced a file or the end of the repository's history.
To address the problem, we now read the file's content at the previous commit in the repo. The code fails gracefully, if git returns an error when attempting to read the file.
=> Fix reading with limit and global-revisions

cmd/console.go, cmd/html_report.go, cmd/paths.go, cmd/paths_test.go, cmd/report.go, cmd/summary.go, git/read_local.go, git/read_local_test.go
Some clean up as promised in #164.
=> Ensure git is always given an absolute repo path

cmd/html_report.go
fix 
https://github.com/pb33f/openapi-changes/issues/194
create a dedicated function to handle the error and call it from the various places 
notice it unifies access right was 0664 or 0744 , keep only 0744
=> fix right left comparison in case of error

cmd/summary.go
Hey!
This is an implementation of what I opened as an issue in #198. Adding the `--error-on-diff` flag to the `summary` command will make the tool terminate with an error on any (be it non-breaking or breaking) differences. This basically has the same effect as [the --fail-on-diff flag in oasdiff tool](https://github.com/oasdiff/oasdiff/blob/main/docs/DIFF.md#preventing-changes).
Let me know your thoughts.
=> feat: add error-on-diff flag for summary command

cmd/console.go, cmd/html_report.go, cmd/report.go, cmd/root.go, cmd/summary.go, git/github.go, git/read_local.go, git/read_local_test.go
Adds a `--base-commit` flag, which is used as the oldest commit to compare against. This is particularly useful in a PR situation, where you want to compare against changes that occurred in the PR only.
Note that it doesn't check the differences inside of the base commit, rather, the base commit is considered the "start" of the history.
Examples:
```console
$ openapi-changes summary \
--limit 100 \
--base-commit '89e8d64ac465dfd4cd11c20606df54a40943cca0' \
./ sample-specs/petstorev3.json
$ openapi-changes summary \
--limit 100 \
--base-commit '89e8d64ac465dfd4cd11c20606df54a40943cca0' \
'https://github.com/pb33f/openapi-changes/commits/main/sample-specs/petstorev3.json'
```
This is a simpler implementation of something like what golangci-lint does, with `--new-from-rev`. With the …
=> feat: support base commit-based checks
